# iotivity-c
Iotivity C SDK

== docs

cod/operations.adoc has a concise summary of the kernel C API.

== examples

To compile and run the examples you need a working installation of the Iotivity dev kit.

Edit `source.me` and then `$ source source.me`.

Then:

[source,sh]
----
$ make server
$ make client
----


If you run into link problems on OS X use `install_name_tool`.  See
also `$ man ld`, search for "install_name".

For example, for the minimal example, to build just run `make`.  Then
run the server: `./server -o 0`.  Then in another terminal run one of
the examples that come with the official dev kit, such as
`resource/examples/presenceclient` or
`resource/examples/devicediscoveryclient`.  Be sure to run the server
first, then the client.

== debugging

==== OS X

The standard debugger is http://lldb.llvm.org/[lldb], not GNU gdb.

Also, it looks like lldb might ignore DYLD_LIBRARY_PATH, so you might
have to use `install_name_tool` to fix up your links.  Use `otool -L`
to see the links.

== profiling


=== misc

style guidelines: https://www.kernel.org/doc/Documentation/CodingStyle

